# Generated by Django 2.0 on 2019-09-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_auto_20190925_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='recall_geography',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
