# Generated by Django 2.1 on 2020-05-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0005_auto_20200113_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='activity_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_area', to='addressapp.Activity'),
        ),
    ]
