# Generated by Django 2.1 on 2020-06-01 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0006_auto_20200527_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='geography',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_geography', to='addressapp.Ward'),
        ),
    ]
