# Generated by Django 2.0 on 2019-09-25 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encounter',
            old_name='other_detail',
            new_name='other_problem',
        ),
    ]
