# Generated by Django 2.0 on 2019-11-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0002_auto_20190925_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='high_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='low_blood_pressure',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='history',
            name='thyroid_disorder',
            field=models.BooleanField(default=False),
        ),
    ]
