# Generated by Django 2.1 on 2020-01-13 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0003_auto_20191113_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='created_at',
            field=models.DateField(db_index=True),
        ),
    ]
