# Generated by Django 2.1 on 2020-05-27 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0004_auto_20200113_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='activity_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_area', to='addressapp.Activity'),
        ),
    ]
