# Generated by Django 2.1 on 2020-06-15 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0006_auto_20200601_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='reason_for_deletion',
            field=models.CharField(choices=[('accidental_entry', 'Accidental Entry'), ('duplicate_encounter', 'Duplicate Encounter'), ('incorrect_patient', 'Incorrect Patient'), ('incorrect_user', 'Incorrect User'), ('other', 'Other')], default='accidental_entry', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='reason_for_modification',
            field=models.TextField(default='just'),
        ),
    ]
