# Generated by Django 2.1 on 2020-06-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0008_auto_20200615_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Pending '), ('approved', 'Approved'), ('Deny', 'Deny')], default='pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='encounter',
            name='modify_status',
            field=models.CharField(choices=[('pending', 'Pending '), ('approved', 'Approved'), ('Deny', 'Deny')], default='pending', max_length=100, null=True),
        ),
    ]
