# Generated by Django 2.1 on 2020-06-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0009_auto_20200615_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='delete_status',
            field=models.CharField(choices=[('none', 'None '), ('pending', 'Pending '), ('approved', 'Approved'), ('Deny', 'Deny')], default='none', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='modify_status',
            field=models.CharField(choices=[('none', 'None '), ('pending', 'Pending '), ('approved', 'Approved'), ('Deny', 'Deny')], default='none', max_length=100, null=True),
        ),
    ]
