# Generated by Django 2.1 on 2020-06-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0010_auto_20200615_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='other_reason_for_deletion',
            field=models.TextField(null=True),
        ),
    ]
