# Generated by Django 2.1 on 2020-06-15 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0011_encounter_other_reason_for_deletion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='reason_for_deletion',
            field=models.CharField(choices=[('none', 'None '), ('accidental_entry', 'Accidental Entry'), ('duplicate_encounter', 'Duplicate Encounter'), ('incorrect_patient', 'Incorrect Patient'), ('incorrect_user', 'Incorrect User'), ('other', 'Other')], default='none', max_length=100, null=True),
        ),
    ]
