# Generated by Django 2.1 on 2020-06-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0012_auto_20200615_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='delete_status',
            field=models.CharField(choices=[('none', 'None '), ('pending', 'Pending '), ('approved', 'Approved'), ('Deny', 'Deny')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='reason_for_deletion',
            field=models.CharField(choices=[('none', 'None '), ('accidental_entry', 'Accidental Entry'), ('duplicate_encounter', 'Duplicate Encounter'), ('incorrect_patient', 'Incorrect Patient'), ('incorrect_user', 'Incorrect User'), ('other', 'Other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='encounter',
            name='reason_for_modification',
            field=models.TextField(null=True),
        ),
    ]
