# Generated by Django 2.1 on 2020-06-16 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0016_auto_20200615_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounter',
            name='delete_status',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='modify_status',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='other_reason_for_deletion',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='reason_for_deletion',
        ),
        migrations.RemoveField(
            model_name='encounter',
            name='reason_for_modification',
        ),
    ]
