# Generated by Django 2.1 on 2020-06-16 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0017_auto_20200616_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifyDelete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_for_modification', models.TextField(default='')),
                ('modify_status', models.CharField(choices=[('pending', 'Pending '), ('approved', 'Approved'), ('Deny', 'Deny')], default='', max_length=100)),
                ('reason_for_deletion', models.CharField(choices=[('accidental_entry', 'Accidental Entry'), ('duplicate_encounter', 'Duplicate Encounter'), ('incorrect_patient', 'Incorrect Patient'), ('incorrect_user', 'Incorrect User'), ('other', 'Other')], default='', max_length=100)),
                ('other_reason_for_deletion', models.TextField(default='')),
                ('delete_status', models.CharField(choices=[('pending', 'Pending '), ('approved', 'Approved'), ('Deny', 'Deny')], default='', max_length=100)),
                ('flag', models.CharField(choices=[('modify', 'Modify '), ('delete', 'Delete')], default='', max_length=100)),
                ('encounter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encounter_modify_delete', to='encounterapp.Encounter')),
            ],
        ),
    ]
