# Generated by Django 2.1 on 2020-06-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0018_modifydelete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifydelete',
            name='flag',
            field=models.CharField(choices=[('modify', 'Modify '), ('delete', 'Delete')], max_length=100),
        ),
    ]
