# Generated by Django 2.1 on 2020-06-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0019_auto_20200616_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifydelete',
            name='modify_approved_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='modifydelete',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Pending '), ('approved', 'Approved'), ('denied', 'Denied'), ('modified', 'Modified'), ('deleted', 'Deleted')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='modifydelete',
            name='modify_status',
            field=models.CharField(choices=[('pending', 'Pending '), ('approved', 'Approved'), ('denied', 'Denied'), ('modified', 'Modified'), ('deleted', 'Deleted')], default='', max_length=100),
        ),
    ]
