# Generated by Django 2.1 on 2020-06-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0021_auto_20200617_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='created_at',
            field=models.DateTimeField(db_index=True),
        ),
    ]
