# Generated by Django 2.1 on 2020-06-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0022_auto_20200624_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifydelete',
            name='modify_status',
            field=models.CharField(choices=[('pending', 'Pending '), ('approved', 'Approved'), ('modified', 'Modified'), ('expired', 'Expired')], default='', max_length=100),
        ),
    ]
