# Generated by Django 2.1 on 2020-07-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0023_auto_20200625_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounter',
            name='created_at',
            field=models.DateField(db_index=True),
        ),
    ]
