# Generated by Django 2.1 on 2020-07-20 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('encounterapp', '0025_auto_20200710_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifydelete',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
