# Generated by Django 2.1 on 2020-07-28 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0026_modifydelete_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifydelete',
            name='modify_expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
