# Generated by Django 2.1 on 2020-07-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0027_modifydelete_modify_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifydelete',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='modifydelete',
            name='restore_expiry_date',
            field=models.DateTimeField(null=True),
        ),
    ]
