# Generated by Django 2.1 on 2020-07-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0028_auto_20200728_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
