# Generated by Django 2.1 on 2020-07-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0029_encounter_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='request_counter',
            field=models.IntegerField(default=0),
        ),
    ]
