# Generated by Django 2.1 on 2020-08-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0031_auto_20200730_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifydelete',
            name='delete_status',
            field=models.CharField(choices=[('pending', 'Pending '), ('deleted', 'Deleted'), ('rejected', 'Rejected')], default='', max_length=100),
        ),
    ]
