# Generated by Django 2.1 on 2020-08-04 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0032_auto_20200801_1914'),
        ('encounterapp', '0032_auto_20200801_1758'),
    ]

    operations = [
    ]
