# Generated by Django 2.1 on 2020-08-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0033_merge_20200804_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifydelete',
            name='reason_for_modification',
            field=models.TextField(null=True),
        ),
    ]
