# Generated by Django 2.1 on 2020-08-09 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0033_merge_20200804_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='server_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
