# Generated by Django 2.1 on 2020-08-10 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encounterapp', '0034_encounter_server_date'),
        ('encounterapp', '0035_auto_20200810_1621'),
    ]

    operations = [
    ]
